# Generated by Django 4.0.5 on 2022-06-02 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('digipal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('attribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='digipal.contentattribution')),
                ('item_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_contents', to='digipal.itempart')),
                ('languages', models.ManyToManyField(blank=True, related_name='text_contents', to='digipal.language')),
                ('text', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_contents', to='digipal.text')),
            ],
            options={
                'verbose_name': 'Text (meta)',
                'verbose_name_plural': 'Texts (meta)',
            },
        ),
        migrations.CreateModel(
            name='TextContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Text Type',
                'verbose_name_plural': 'Text Types',
            },
        ),
        migrations.CreateModel(
            name='TextContentXMLStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('sort_order', models.IntegerField(default=0, help_text='The order of this status in your workflow.')),
            ],
            options={
                'verbose_name': 'Text Status',
                'verbose_name_plural': 'Text Statuses',
            },
        ),
        migrations.CreateModel(
            name='TextPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('pattern', models.CharField(blank=True, max_length=1000, null=True)),
                ('order', models.IntegerField(db_index=True, default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'key'],
                'unique_together': {('key',)},
            },
        ),
        migrations.CreateModel(
            name='TextContentXML',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('last_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='text_content_xmls', to='digipal.image')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_content_xmls', to='digipal_text.textcontentxmlstatus')),
                ('text_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_content_xmls', to='digipal_text.textcontent')),
            ],
            options={
                'verbose_name': 'Text (XML)',
                'verbose_name_plural': 'Texts (XML)',
                'unique_together': {('text_content',)},
            },
        ),
        migrations.AddField(
            model_name='textcontent',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_contents', to='digipal_text.textcontenttype'),
        ),
        migrations.CreateModel(
            name='TextContentXMLCopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ahash', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.BinaryField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='digipal_text.textcontentxml')),
            ],
            options={
                'verbose_name': 'Text Copy',
                'verbose_name_plural': 'Text Copies',
                'unique_together': {('source', 'ahash')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='textcontent',
            unique_together={('item_part', 'type')},
        ),
        migrations.CreateModel(
            name='TextAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elementid', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textannotations', to='digipal.annotation')),
            ],
            options={
                'unique_together': {('annotation', 'elementid')},
            },
        ),
        migrations.CreateModel(
            name='EntryHand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_number', models.CharField(db_index=True, max_length=20)),
                ('hand_label', models.CharField(db_index=True, max_length=20)),
                ('order', models.IntegerField(db_index=True, default=0)),
                ('correction', models.BooleanField(db_index=True, default=False)),
                ('certainty', models.FloatField(default=1.0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('item_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_hands', to='digipal.itempart')),
            ],
            options={
                'unique_together': {('item_part', 'entry_number', 'hand_label', 'order', 'correction')},
            },
        ),
    ]
