# Generated by Django 5.0.6 on 2024-05-17 18:09

import digipal.iipfield.storage
import iipimage.fields
import iipimage.storage
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("digipal", "0002_alter_image_iipimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="iipimage",
            field=iipimage.fields.ImageField(
                blank=True,
                max_length=200,
                null=True,
                storage=iipimage.storage.ImageStorage(
                    base_url="http://localhost/iip/iipsrv.fcgi",
                    location="/home/digipal/images/",
                ),
                upload_to=digipal.iipfield.storage.get_image_path,
            ),
        ),
    ]
