# Generated by Django 5.0.6 on 2024-05-25 12:47

import digipal.iipfield.storage
import iipimage.fields
import iipimage.storage
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digipal', '0003_alter_image_iipimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='iipimage',
            field=iipimage.fields.ImageField(blank=True, max_length=200, null=True, storage=iipimage.storage.ImageStorage(base_url='http://localhost/iip/iipsrv.fcgi', location='/Users/luca/Documents/digipal/digipal_project/images'), upload_to=digipal.iipfield.storage.get_image_path),
        ),
    ]
